{% set version = "3.4.4" %}

package:
  name: chaquopy-libffi
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/libffi/libffi/releases/download/v{{ version }}/libffi-{{ version }}.tar.gz
